### ISSUE TITLE
Issue in connecting filebeat to graylog

### ISSUE THREAD

**Issue by abhatt4** [sivasamyk/graylog-beats-plugin#3]
Hi,

I got this exception on the graylog-server logs after doing the said changes.

0 WARN [LumberjackServer] Exception while creating channel pipeline
java.io.FileNotFoundException: admin (No such file or directory)
at java.io.FileInputStream.open(Native Method)
at java.io.FileInputStream.(FileInputStream.java:146)
at java.io.FileInputStream.(FileInputStream.

am using filebeat 1.1.1 to send the logs, to graylog server with following output defined,

logstash:
# The Logstash hosts

hosts: ["X.X.XX.X:5044"]

I have configured the plugin and have defined the input as beat listening to 5044 port.

On the graylog server i have

graylog-server 1.3.3
graylog-web 1.3.3
elasticsearch 1.7.3.

Do i have to do any other change on the graylog server side. I did what was written in here. Help will be appreciated.

**Comment by sivasamyk** [comment]
Please paste the complete logs with stacktrace from graylog server.

**Comment by abhatt4** [comment]
2016-03-04T16:19:31.986+05:30 WARN  [LumberjackServer] Exception while creating channel pipeline
java.io.FileNotFoundException: admin (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at org.graylog.inputs.beats.server.LumberjackServer.getSSLEngine(LumberjackServer.java:65)
        at org.graylog.inputs.beats.server.LumberjackServer.access$100(LumberjackServer.java:24)
        at org.graylog.inputs.beats.server.LumberjackServer$1.getPipeline(LumberjackServer.java:46)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-03-04T16:19:31.988+05:30 WARN  [AbstractNioSelector] Failed to initialize an accepted socket.
java.io.FileNotFoundException: admin (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at org.graylog.inputs.beats.server.LumberjackServer.getSSLEngine(LumberjackServer.java:65)
        at org.graylog.inputs.beats.server.LumberjackServer.access$100(LumberjackServer.java:24)
        at org.graylog.inputs.beats.server.LumberjackServer$1.getPipeline(LumberjackServer.java:46)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-03-04T16:20:31.994+05:30 WARN  [LumberjackServer] Exception while creating channel pipeline
java.io.FileNotFoundException: admin (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at org.graylog.inputs.beats.server.LumberjackServer.getSSLEngine(LumberjackServer.java:65)
        at org.graylog.inputs.beats.server.LumberjackServer.access$100(LumberjackServer.java:24)
        at org.graylog.inputs.beats.server.LumberjackServer$1.getPipeline(LumberjackServer.java:46)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-03-04T16:20:31.996+05:30 WARN  [AbstractNioSelector] Failed to initialize an accepted socket.
java.io.FileNotFoundException: admin (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at org.graylog.inputs.beats.server.LumberjackServer.getSSLEngine(LumberjackServer.java:65)
        at org.graylog.inputs.beats.server.LumberjackServer.access$100(LumberjackServer.java:24)
        at org.graylog.inputs.beats.server.LumberjackServer$1.getPipeline(LumberjackServer.java:46)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-03-04T16:20:33.307+05:30 INFO  [AbstractValidatingSessionManager] Validating all active sessions...
2016-03-04T16:20:33.311+05:30 INFO  [AbstractValidatingSessionManager] Finished session validation.  No sessions were stopped.
2016-03-04T16:21:32.005+05:30 WARN  [LumberjackServer] Exception while creating channel pipeline
java.io.FileNotFoundException: admin (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at org.graylog.inputs.beats.server.LumberjackServer.getSSLEngine(LumberjackServer.java:65)
        at org.graylog.inputs.beats.server.LumberjackServer.access$100(LumberjackServer.java:24)
        at org.graylog.inputs.beats.server.LumberjackServer$1.getPipeline(LumberjackServer.java:46)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-03-04T16:21:32.007+05:30 WARN  [AbstractNioSelector] Failed to initialize an accepted socket.
java.io.FileNotFoundException: admin (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at org.graylog.inputs.beats.server.LumberjackServer.getSSLEngine(LumberjackServer.java:65)
        at org.graylog.inputs.beats.server.LumberjackServer.access$100(LumberjackServer.java:24)
        at org.graylog.inputs.beats.server.LumberjackServer$1.getPipeline(LumberjackServer.java:46)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-03-04T16:22:32.015+05:30 WARN  [LumberjackServer] Exception while creating channel pipeline
java.io.FileNotFoundException: admin (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at org.graylog.inputs.beats.server.LumberjackServer.getSSLEngine(LumberjackServer.java:65)
        at org.graylog.inputs.beats.server.LumberjackServer.access$100(LumberjackServer.java:24)
        at org.graylog.inputs.beats.server.LumberjackServer$1.getPipeline(LumberjackServer.java:46)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-03-04T16:22:32.017+05:30 WARN  [AbstractNioSelector] Failed to initialize an accepted socket.
java.io.FileNotFoundException: admin (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at org.graylog.inputs.beats.server.LumberjackServer.getSSLEngine(LumberjackServer.java:65)
        at org.graylog.inputs.beats.server.LumberjackServer.access$100(LumberjackServer.java:24)
        at org.graylog.inputs.beats.server.LumberjackServer$1.getPipeline(LumberjackServer.java:46)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-03-04T16:23:32.022+05:30 WARN  [LumberjackServer] Exception while creating channel pipeline
java.io.FileNotFoundException: admin (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at org.graylog.inputs.beats.server.LumberjackServer.getSSLEngine(LumberjackServer.java:65)
        at org.graylog.inputs.beats.server.LumberjackServer.access$100(LumberjackServer.java:24)
        at org.graylog.inputs.beats.server.LumberjackServer$1.getPipeline(LumberjackServer.java:46)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-03-04T16:23:32.025+05:30 WARN  [AbstractNioSelector] Failed to initialize an accepted socket.
java.io.FileNotFoundException: admin (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at org.graylog.inputs.beats.server.LumberjackServer.getSSLEngine(LumberjackServer.java:65)
        at org.graylog.inputs.beats.server.LumberjackServer.access$100(LumberjackServer.java:24)
        at org.graylog.inputs.beats.server.LumberjackServer$1.getPipeline(LumberjackServer.java:46)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-03-04T16:24:32.032+05:30 WARN  [LumberjackServer] Exception while creating channel pipeline
java.io.FileNotFoundException: admin (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at org.graylog.inputs.beats.server.LumberjackServer.getSSLEngine(LumberjackServer.java:65)
        at org.graylog.inputs.beats.server.LumberjackServer.access$100(LumberjackServer.java:24)
        at org.graylog.inputs.beats.server.LumberjackServer$1.getPipeline(LumberjackServer.java:46)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-03-04T16:24:32.034+05:30 WARN  [AbstractNioSelector] Failed to initialize an accepted socket.
java.io.FileNotFoundException: admin (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at org.graylog.inputs.beats.server.LumberjackServer.getSSLEngine(LumberjackServer.java:65)
        at org.graylog.inputs.beats.server.LumberjackServer.access$100(LumberjackServer.java:24)
        at org.graylog.inputs.beats.server.LumberjackServer$1.getPipeline(LumberjackServer.java:46)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-03-04T16:25:32.043+05:30 WARN  [LumberjackServer] Exception while creating channel pipeline
java.io.FileNotFoundException: admin (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at org.graylog.inputs.beats.server.LumberjackServer.getSSLEngine(LumberjackServer.java:65)
        at org.graylog.inputs.beats.server.LumberjackServer.access$100(LumberjackServer.java:24)
        at org.graylog.inputs.beats.server.LumberjackServer$1.getPipeline(LumberjackServer.java:46)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-03-04T16:25:32.044+05:30 WARN  [AbstractNioSelector] Failed to initialize an accepted socket.
java.io.FileNotFoundException: admin (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at org.graylog.inputs.beats.server.LumberjackServer.getSSLEngine(LumberjackServer.java:65)
        at org.graylog.inputs.beats.server.LumberjackServer.access$100(LumberjackServer.java:24)
        at org.graylog.inputs.beats.server.LumberjackServer$1.getPipeline(LumberjackServer.java:46)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorke

**Comment by abhatt4** [comment]
Here is the output for  filebeat -v -e -c /etc/filebeat/filebeat.yml

 filebeat -v -e -c /etc/filebeat/filebeat.yml
2016/03/04 11:13:22.618389 geolite.go:24: INFO GeoIP disabled: No paths were set under output.geoip.paths
2016/03/04 11:13:22.618585 logstash.go:106: INFO Max Retries set to: 3
2016/03/04 11:13:22.619456 outputs.go:119: INFO Activated logstash as output plugin.
2016/03/04 11:13:22.619630 publish.go:288: INFO Publisher name: xxxxxxxxxx.com
2016/03/04 11:13:22.619896 async.go:78: INFO Flush Interval set to: 1s
2016/03/04 11:13:22.619913 async.go:84: INFO Max Bulk Size set to: 2048
2016/03/04 11:13:22.620034 beat.go:147: INFO Init Beat: filebeat; Version: 1.1.1
2016/03/04 11:13:22.621043 beat.go:173: INFO filebeat sucessfully setup. Start running.
2016/03/04 11:13:22.621103 registrar.go:66: INFO Registry file set to: /root/.filebeat
2016/03/04 11:13:22.621147 prospector.go:127: INFO Set ignore_older duration to 24h0m0s
2016/03/04 11:13:22.621161 prospector.go:127: INFO Set scan_frequency duration to 10s
2016/03/04 11:13:22.621173 prospector.go:87: INFO Input type set to: log
2016/03/04 11:13:22.621182 prospector.go:127: INFO Set backoff duration to 1s
2016/03/04 11:13:22.621191 prospector.go:127: INFO Set max_backoff duration to 10s
2016/03/04 11:13:22.621200 prospector.go:107: INFO force_close_file is disabled
2016/03/04 11:13:22.621225 prospector.go:137: INFO Starting prospector of type: log
2016/03/04 11:13:22.621333 crawler.go:78: INFO All prospectors initialised with 0 states to persist
2016/03/04 11:13:22.621351 registrar.go:83: INFO Starting Registrar
2016/03/04 11:13:22.621385 publish.go:88: INFO Start sending events to output
2016/03/04 11:13:22.621443 spooler.go:77: INFO Starting spooler: spool_size: 2048; idle_timeout: 5s
2016/03/04 11:13:22.621553 log.go:113: INFO Harvester started for file: /var/log/messages
2016/03/04 11:13:22.671413 single.go:76: INFO Error publishing events (retrying): EOF
2016/03/04 11:13:22.671450 single.go:152: INFO send fail
2016/03/04 11:13:22.671463 single.go:159: INFO backoff retry: 1s
2016/03/04 11:13:23.677909 single.go:76: INFO Error publishing events (retrying): EOF
2016/03/04 11:13:23.677942 single.go:152: INFO send fail
2016/03/04 11:13:23.677959 single.go:159: INFO backoff retry: 2s
2016/03/04 11:13:25.689224 single.go:76: INFO Error publishing events (retrying): read tcp 10.207.86.142:57211->10.202.17.45:5044: read: connection reset by peer
2016/03/04 11:13:25.689263 single.go:152: INFO send fail
2016/03/04 11:13:25.689286 single.go:159: INFO backoff retry: 4s
2016/03/04 11:13:29.694583 single.go:76: INFO Error publishing events (retrying): read tcp 10.207.86.142:57239->10.202.17.45:5044: read: connection reset by peer
2016/03/04 11:13:29.694646 single.go:152: INFO send fail
2016/03/04 11:13:29.694662 single.go:159: INFO backoff retry: 8s
2016/03/04 11:13:37.704561 single.go:76: INFO Error publishing events (retrying): read tcp 10.207.86.142:57308->10.202.17.45:5044: read: connection reset by peer
2016/03/04 11:13:37.704606 single.go:152: INFO send fail
2016/03/04 11:13:37.704620 single.go:159: INFO backoff retry: 16s
2016/03/04 11:13:53.708718 single.go:76: INFO Error publishing events (retrying): read tcp 10.207.86.142:57431->10.202.17.45:5044: read: connection reset by peer
2016/03/04 11:13:53.708767 single.go:152: INFO send fail
2016/03/04 11:13:53.708781 single.go:159: INFO backoff retry: 32s
^C2016/03/04 11:14:06.122776 registrar.go:129: INFO Stopping Registrar
2016/03/04 11:14:06.122824 registrar.go:93: INFO Ending Registrar
2016/03/04 11:14:06.123194 registrar.go:157: INFO Registry file updated. 0 states written.
2016/03/04 11:14:06.123246 beat.go:183: INFO Cleaning up filebeat before shutting down.

**when i do a telnet it closes the connection**am not closing the connection.

telnet xx.xx.xx.xx 5044
Trying xx.xx.xx.xx...
Connected to 1xx.xx.xx.xx.
Escape character is '^]'.
Connection closed by foreign host.
[root@xxxxxl15 ~]# telnet 1xx.xx.xx.xx 5044
Trying 1xx.xx.xx.xx...
Connected to 1xx.xx.xx.xx.
Escape character is '^]'.
Connection closed by foreign host

**Comment by sivasamyk** [comment]
You have enabled SSL transport and the Keystore Path (admin) is wrong. You should provide the absolute path if JKS keystore like /etc/keys/beats.jks

**Comment by abhatt4** [comment]
Thanks a lot that made it work like a charm.
